# Site Settings
locale                   : "en-US"
title                    : "Kun Qian"
title_separator          : "-"
name                    : "Kun Qian"
description             : "Ph.D. Candidate at Peking University"
url                     : "https://kun98.github.io"
baseurl                 : "" 
repository              : "sldyns/kun98.github.io"

# Site Author
author:
  name             : "Kun Qian"
  avatar           : "profile.png"
  bio              : "Ph.D. Candidate in Statistics at Peking University"
  location         : "Beijing, China"
  employer         : "Peking University"
  pubmed           : 
  googlescholar    : "https://scholar.google.com/citations?user=bm54b7kAAAAJ"
  email            : "kunqian@stu.pku.edu.cn"
  researchgate     : "https://www.researchgate.net/profile/Kun-Qian-63" 
  github           : "sldyns"
  linkedin         :
  orcid            : 
  twitter          : 

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true